- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- Dockerfile
- go.sum
- pkg/onboarding/application/exceptions/custom_errors.go
- pkg/onboarding/application/exceptions/custom_errors_test.go
- pkg/onboarding/application/exceptions/error_messages.go
- pkg/onboarding/domain/model/models_gen.go
- pkg/onboarding/infrastructure/database/fb/firebase.go
- pkg/onboarding/presentation/graph/generated/generated.go
- pkg/onboarding/presentation/graph/inputs.graphql
- pkg/onboarding/repository/mock/onboarding.go
- tests/survey_acceptance_test.go
Signed-off-by: Otieno Calvine <nyarangaotieno@gmail.com>
> chore: remove unused env vars and configurations

- .github/workflows/deployment.yaml
Port prod deployment from onboarding library
Signed-off-by: Otieno Calvine <nyarangaotieno@gmail.com>
> chore: port deployment stage

- .github/workflows/ci.yml
- deps.yaml
- go.mod
- go.sum
- pkg/onboarding/infrastructure/infrastructure.go
- pkg/onboarding/presentation/config.go
- pkg/onboarding/presentation/interactor/interactor.go
- pkg/onboarding/usecases/config_test.go
- pkg/onboarding/usecases/profile.go
- pkg/onboarding/usecases/signup.go
- pkg/onboarding/usecases/signup_integration_test.go
- pkg/onboarding/usecases/usecase.go
- pkg/onboarding/usecases/usecases.go
> chore: add signup usecase implementation

- .github/workflows/ci.yml
- pkg/onboarding/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/onboarding/infrastructure/database/postgres/mock/pg_mock.go
- pkg/onboarding/infrastructure/database/postgres/pg_create.go
- pkg/onboarding/infrastructure/database/postgres/pg_create_test.go
Depend on postgreSQL docker image for integration tests
Write mocks for unit testing
Signed-off-by: Otieno Calvine <nyarangaotieno@gmail.com>
> chore: wire up ci configuration and unit tests

- .github/workflows/deployment.yaml
> chore: add database envs

- pkg/mycarehub/presentation/config.go
> fix: minor tweaks

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/client.graphql
- pkg/mycarehub/presentation/graph/client.resolvers.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/interactor/interactor.go
- pkg/mycarehub/usecases/client/client.go
- pkg/mycarehub/usecases/facility/config_test.go
- pkg/mycarehub/usecases/mock/usecase_mock.go
- pkg/mycarehub/usecases/user/user.go
> feat: implement creating a user with a client profile

- go.mod
- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/profile.graphql
- pkg/mycarehub/presentation/graph/profile.resolvers.go
- pkg/mycarehub/presentation/interactor/interactor.go
- pkg/mycarehub/usecases/facility/config_test.go
- pkg/mycarehub/usecases/mock/usecase_mock.go
- pkg/mycarehub/usecases/user/user.go
This adds the functionality for setting a user pin. It can be used to
set a PIN for the first time or even change the pin, on first login
after invite or after a pin expires
> feat: add set user pin API

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/enums/filter_type.go
- pkg/mycarehub/application/enums/filter_types_validator.go
- pkg/mycarehub/application/enums/filtercategories_type.go
- pkg/mycarehub/domain/models.go
- pkg/mycarehub/domain/pagination.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/helpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/mock/usecase_mock.go
> feat: paginate facilities

- .github/workflows/deployment.yaml
The deployment pipeline is updated to: When we merge to develop, it
deploys to the testing environment and when we deploy to main branch, it
deploys to prod.
> fix: update deployment pipeline

- README.md
- go.mod
- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/mock/usecase_mock.go
- pkg/mycarehub/usecases/user/user.go
> feat: implement login by phone

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/enums/filter_type.go
- pkg/mycarehub/domain/models.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/helpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> feat: filter facilities

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
> test: add gorm integration tests

- .github/workflows/deployment.yaml
- README.md
> chore: publish schema to test schema registry

- .github/workflows/deployment.yaml
> fix: add Schema Registry CLI command version

- .github/workflows/deployment.yaml
> fix: add schema registry URL env variable

- .github/workflows/deployment.yaml
> fix: add url flag argument to push schema command

- .github/workflows/deployment.yaml
> chore: publish schema to prod schema registry

- go.mod
- go.sum
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> Add user unit test

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/usecases/facility/facility_integration_test.go
> feat: search facilities

- pkg/mycarehub/usecases/facility/facility_integration_test.go
> add facility integration tests

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
> chore: fix registry URL env

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/enums/filter_type.go
- pkg/mycarehub/application/enums/filter_types_validator.go
- pkg/mycarehub/application/enums/filtercategories_type.go
- pkg/mycarehub/application/enums/sort_type.go
- pkg/mycarehub/domain/models.go
- pkg/mycarehub/domain/pagination.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/helpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> feat: sort facilities

- .github/workflows/deployment.yaml
> fix: add environment name to push schema stage

- .github/workflows/deployment.yaml
> fix: add environment name to push schema stage 

- pkg/mycarehub/application/enums/client_type_test.go
- pkg/mycarehub/application/enums/contact_type_test.go
> chore: add enum tests

- pkg/mycarehub/usecases/user/user_integration_test.go
> add user integration tests

- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
> tests: add more tests

- pkg/mycarehub/application/enums/client_type_test.go
- pkg/mycarehub/application/enums/contact_type.go
- pkg/mycarehub/application/enums/counties_of_country_test.go
- pkg/mycarehub/application/enums/country_types_test.go
- pkg/mycarehub/application/enums/county_types_test.go
> add county enum tests

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
> chore: setup staging deployment

- pkg/mycarehub/application/enums/counties_of_country_test.go
- pkg/mycarehub/application/enums/filter_type_test.go
- pkg/mycarehub/application/enums/filter_types_validator_test.go
- pkg/mycarehub/application/enums/filtercategories_type_test.go
- pkg/mycarehub/application/enums/identifier_test.go
- pkg/mycarehub/application/enums/metrics.go
- pkg/mycarehub/application/enums/metrics_test.go
- pkg/mycarehub/application/enums/role_type.go
- pkg/mycarehub/application/enums/role_type_test.go
- pkg/mycarehub/application/enums/sort_type.go
- pkg/mycarehub/application/enums/sort_type_test.go
- pkg/mycarehub/application/enums/user_adress_type_test.go
- pkg/mycarehub/application/enums/usertype.go
- pkg/mycarehub/application/enums/usertype_test.go
> add more enum test

- .github/workflows/deployment.yaml
> chore: add build docker image stage

- go.sum
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/application/extension/onboarding.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/mock/utils_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> add user usecase unit test

- pkg/mycarehub/usecases/client/client_integration_test.go
> add client registration integration test

- pkg/mycarehub/application/utils/helpers.go
> chore: add docstring

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/usecases/user/user.go
> fix: fix get user by phone gorm logic

- docs/index.md
This is the eventual home for published project documentation e.g API docs.
This PR should be considered a setup / housekeeping step. Once the commit makes its way to `main`, Github pages should be correctly initialized (to be confirmed). After that, documentation content will be added.
> chore: initialize docs/ folder for github-pages

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- pkg/mycarehub/usecases/user/user_integration_test.go
> feat:add inactivate facility feature

- tests/config_test.go
- tests/facility_acceptance_test.go
> test: setup initial acceptance tests

- go.mod
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> feat:add facility re-activation feature

- tests/config_test.go
- tests/facility_acceptance_test.go
> chore: add inactivate and re-activate facility acceptance tests

- .github/workflows/ci.yml
- scripts/coverage.sh
> chore: enforce test coverage threshold

- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
> fix:change get terms from mutation to query

- pkg/mycarehub/domain/terms.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/terms/mock/terms_mock.go
- pkg/mycarehub/usecases/terms/terms.go
- pkg/mycarehub/usecases/terms/terms_unit_test.go
> chore:refactor get all terms of service

- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- tests/config_test.go
> chore: remove unused code

- go.mod
- pkg/mycarehub/domain/terms.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/terms/mock/terms_mock.go
> chore:change terms ID from string to int

- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/terms/mock/terms_mock.go
- pkg/mycarehub/usecases/terms/terms.go
- pkg/mycarehub/usecases/terms/terms_unit_test.go
- pkg/mycarehub/usecases/user/user_integration_test.go
- tests/config_test.go
> feat: add accept terms api

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/profile.graphql
- pkg/mycarehub/presentation/graph/profile.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: implement set pin

- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: implement login API

- pkg/mycarehub/application/enums/securityquestionstype.go
- pkg/mycarehub/application/enums/securityquestionstype_test.go
- pkg/mycarehub/domain/security_questions.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/securityquestion.graphql
- pkg/mycarehub/presentation/graph/securityquestion.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/interactor/interactor.go
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/securityquestions/mock/security_questions.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/user/user_integration_test.go
- tests/config_test.go
> feat:feat get all security questions

- .gitignore
- browser_detect/__init__.py
- browser_detect/main.py
- browser_detect/requirements.txt
> feat: add browser and OS detection script

- pkg/mycarehub/application/exceptions/cusstom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/application/exceptions/model_test.go
- pkg/mycarehub/application/exceptions/models.go
- pkg/mycarehub/infrastructure/database/postgres/mappers_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/terms/terms.go
- pkg/mycarehub/usecases/user/user.go
> chore: setup errorcodes

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_integration_test.go
- pkg/mycarehub/usecases/otp/otp_test.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/terms/terms_test.go
> feat: verify otp endpoint

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_integration_test.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
> chore:fix verify otp

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: update login response

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/usecases/otp/otp_integration_test.go
> chore:invalidate old OTPs when new one is generated

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/config_test.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: implement request pin reset API endpoint

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_integration_test.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/terms/terms_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: code clean up

- pkg/mycarehub/usecases/user/user.go
> fix: remove `accepted terms` login check

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/external_test.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_integration_test.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/terms/terms_test.go
> feat:add retry send otp endpoint

- go.mod
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/user.go
> feat: add a complete onboarding tour API

- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: assorted fixes

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_integration_test.go
- pkg/mycarehub/usecases/securityquestions/mock/security_questions.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/terms/terms_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
> Get user answered security questions

- .github/workflows/deployment.yaml
- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/domain/content.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/usecases.go
> feat: implement get content API

- pkg/mycarehub/usecases/user/user.go
> fix: set invite pin to expire after an hour

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/content/mock/content_mock.go
> feat: share content

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_test.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/content/mock/content_mock.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
> feat: add like content api

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/content/content.go
> feat: view content

- pkg/mycarehub/application/enums/securityquestionstype.go
- pkg/mycarehub/application/enums/securityquestionstype_test.go
- pkg/mycarehub/domain/security_questions.go
- pkg/mycarehub/domain/security_questions_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/securityquestions/mock/security_questions_mock.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
> chore: fix response type enums

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: add a refresh token endpoint

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/enums/healthdiary.go
- pkg/mycarehub/application/enums/healthdiary_test.go
- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
- pkg/mycarehub/usecases/usecases.go
> feat: create healthdiary entry API

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
> feat: can record mood

- pkg/mycarehub/domain/health_diary.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
> feat: get random quote

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
> feat: check if user bookmarked content

- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: fetch a client's health diary entries

- .github/workflows/ci.yml
- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: verify pin for acessing sensitive content

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/domain/facility.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility_integration_test.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
> feat:fetch facility's hotline number

- .github/workflows/deployment.yaml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/domain/faq.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/faq.graphql
- pkg/mycarehub/presentation/graph/faq.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/faq/faq.go
- pkg/mycarehub/usecases/faq/faq_test.go
- pkg/mycarehub/usecases/faq/mock/faq_mock.go
- pkg/mycarehub/usecases/usecases.go
> feat: get faq content

- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
> chore: onboarding assorted fixes

- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/presentation/rest/handlers.go
> fix:fix login response

- pkg/mycarehub/domain/content.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> fix:restore duration in featured media

- .github/workflows/deployment.yaml
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
> chore: fix empty query returns

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- go.mod
- go.sum
This server will be used internally by the development team for test
purposes. This intends to eliminate the need for interacting
with the testing database directly.
> chore: setup a staging server

- .github/workflows/deployment.yaml
> fix: auto update traffic assignments

- .github/workflows/ci.yml
- pkg/mycarehub/domain/category.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> fix:return the correct icon url when listing categories

- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: add date field to user bookmarked content

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/usecases.go
> feat: add service request API

- pkg/mycarehub/usecases/content/content.go
> fix: return all content payload when fetching bookmarked content

- .github/workflows/ci.yml
- pkg/mycarehub/domain/content.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> chore: return document urls

- .github/workflows/ci.yml
> fix ci error

- pkg/mycarehub/presentation/graph/faq.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/faq/README.md
> chore:document FAQs api docs

- pkg/mycarehub/usecases/content/README.md
> chore:document content API(s)

- .github/workflows/ci.yml
> revert ci fix

- pkg/mycarehub/domain/terms.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/terms/terms.go
- pkg/mycarehub/usecases/terms/terms_unit_test.go
> chore:add flavour to terms of service

- pkg/mycarehub/domain/user.go
> chore:fix login response json tags

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/enums/servicerequest_status.go
- pkg/mycarehub/application/enums/servicerequest_status_test.go
- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/application/enums/servicerequest_types_test.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/servicerequest/README.md
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: get service requests

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore:check for pin flavour when logging in or invalidating pin

- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: create service request

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> fix: get service request

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
> fix: health diary entry time

- fixtures/clients_servicerequest.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/README.md
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: Resolve service request

- pkg/mycarehub/usecases/user/user.go
> chore:fix pin flavour

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_messages.go
> chore: fix exceptions error message

- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> refactor: refactor service requests

- fixtures/clients_servicerequest.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/resolver.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: get service request count

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> chore: return `staff facility` in login response

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: return error message when client registration fails

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/user/user.go
This fix adds a bool `inviteClient` to the API. If true, the client is
registered and an invite is sent immediately.
> chore: invite client after registration

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/repository/mock/onboarding.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
> refactor: service request fixes

- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/application/enums/servicerequest_types_test.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> refactor: fix service requests count

- browser_detect/main.py
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: add `flavour` field when searching user by phone

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- go.mod
- go.sum
- pkg/mycarehub/infrastructure/services/stream/stream.go
- pkg/mycarehub/infrastructure/services/stream/stream_test.go
- pkg/mycarehub/usecases/communities/communities.go
> feat: setup getstream library

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: create getstream user when registering a client

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/domain/getstream.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
- pkg/mycarehub/usecases/usecases.go
> feat: query all stream users

- fixtures/communities.yml
- go.mod
- gqlgen.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
> feat:create community

- pkg/mycarehub/domain/getstream.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/scalar.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: list getstream channels

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/usecases/communities/communities.go
> chore: add channel creator to a channel as a member

- .gitignore
- pkg/mycarehub/domain/content.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> chore: fix content api

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: add refresh getstream token API

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/domain/authority.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/authority/authority_test.go
- pkg/mycarehub/usecases/authority/mock/authority_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: add user roles and permissions to login payload

- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: delete getstream channel

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
> feat: reject invitation into a community

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: check whether username already exists

- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: accept community invite

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/authority.graphql
- pkg/mycarehub/presentation/graph/authority.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/authority/authority_test.go
- pkg/mycarehub/usecases/authority/mock/authority_mock.go
> feat: revoke user roles

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: add chv user to payload

- fixtures/communities_community.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
- pkg/mycarehub/usecases/user/user.go
> feat: add users into a group

- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
> feat: remove users from community

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: add moderator to a community

- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: demote moderators

- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: list users invited to a community

- .github/workflows/ci.yml
- go.mod
- go.sum
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/usecases/communities/communities.go
> refactor: use mapstructure to return community metadata

- pkg/mycarehub/usecases/otp/otp.go
> chore: change OTP sms copy depending on flavour

- go.mod
- go.sum
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: recomend clients to channel

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/user.go
> fix: revoke stream token before generating a new one

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/external_test.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: refactor client registration

- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/usecases/communities/communities.go
> fix: recommended community filters

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
This feature allows us to return recently created health diary entries
that will be synced to KenyaEMR. It is fetched based on the last time
syncing happened between myCareHub and KenyaEMR. When the endpoint is
called, all entries that were created after the lastSyncTime will be
returned as part of the response.
- Where necessary, indicate …
> feat: fetch recent health diary entries

- fixtures/clients_client_identifiers.yml
- fixtures/clients_identifier.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: newly registered clients at a facility

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: fetch red flag service request for KenyaEMR

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix:change GET endpoints to use query params

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/domain/screeningtools_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/screeningtools.graphql
- pkg/mycarehub/presentation/graph/screeningtools.resolvers.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
> answer-screening-tool-questions

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> chore: return created time for service request

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/user.go
This PR includes the following fixes:
-  Authenticating the KenyaEMR endpoints
-  Adding a username as part of the extra data for getstream users
-  Changing the getstream token expiry time and making it configurable
- Any new files are updated in the folder …
> chore: assorted fixes

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: update service requests from kenya EMR

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/application/exceptions/models.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: add register staff endpoint

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/appointments/appointment.go
> feat: get client profile by CCC number

- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/domain/screeningtools_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
- pkg/mycarehub/usecases/screeningtools/utils.go
- pkg/mycarehub/usecases/screeningtools/utils_test.go
> feat: create service requests from screening tool responses

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: implement create pin reset service request API

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: search client by ccc number

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
> feat: ban user

- fixtures/clients_client.yml
- fixtures/clients_servicerequest.yml
- fixtures/users_user.yml
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/application/exceptions/model_test.go
- pkg/mycarehub/application/exceptions/models.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: check if client has pending pin reset request

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: implement approve pin reset service request api

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> feat: query banned members

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/domain/authority.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/authority.graphql
- pkg/mycarehub/presentation/graph/authority.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/authority/mock/authority_mock.go
> feat: get user roles

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> fix: create pin reset request by ccc number

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
Reverts savannahghi/mycarehub#307
> Revert "fix: create pin reset request by ccc number"

- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: search staff

- pkg/mycarehub/application/enums/servicerequest_status.go
- pkg/mycarehub/application/enums/servicerequest_status_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> ref: change resolve pin reset service request workflow

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> fixes: search apis assorted fixes

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: implement pin update required

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
> chore: update gcloud set up github action

- fixtures/clients_healthdiaryentry.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
> feat: share health diary entry

- pkg/mycarehub/usecases/user/user.go
> chore:check contact exists before registering client or staff

- .github/workflows/deployment.yaml
- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/service_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
* update client fhir ID
* retrieve user profile
* pubsub create client patient profile
> feat: interservice apis, create patient profile

- fixtures/users_user.yml
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/content/mock/content_mock.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: record failed security questions answering attempts

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
> fix: verify security questions

- pkg/mycarehub/application/enums/servicerequest_status.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
> fix: resolve pin reset request

- pkg/mycarehub/presentation/rest/handlers.go
> chore: add error code to verify security response

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> refactor: refactor service request

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: assorted community fixes

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: reset pin

- pkg/mycarehub/application/enums/communities.go
- pkg/mycarehub/application/enums/communities_test.go
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/communities/mock/communities_mock.go
> feat: query flagged community messages

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: query appointments using provided client identifier

- fixtures/staff_servicerequest.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: verify and resolve staff service request

- pkg/mycarehub/usecases/communities/communities.go
> chore: community assorted fixes

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> chore: fetch both client and staff service request count

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/domain/appointments.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/appointments/appointment_test.go
> feat: get appointment service requests

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: return client CCC number as part of login response

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: register kenyaemr patient

- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: ensure login doesnt fail if ccc number is not found

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
> chore: service request assorted fixes

- pkg/mycarehub/infrastructure/services/getstream/stream.go
> chore: update channel creator role to moderator

- .github/workflows/ci.yml
- pkg/mycarehub/usecases/user/user.go
> chore: handle getstream trial expiry

- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/screeningtools.graphql
- pkg/mycarehub/presentation/graph/screeningtools.resolvers.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
> feat: get facility tool types with responses

- fixtures/clients_clientfacility.yml
- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/screeningtools.graphql
- pkg/mycarehub/presentation/graph/screeningtools.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
> feat: get assement responses

- pkg/mycarehub/usecases/appointments/appointment.go
> chore: add organization id when adding patient record

- go.mod
- go.sum
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
This endpoint will be used by the front-end team to add a push token
to a user's profile. It will be used for push notifications
> feat: register push token API

- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
-  Return CCC Number as part of the healthdiary and service requests response payload
-  Add a key `redFlags` to service requests response
> fix: kenya-emr endpoints assorted fixes

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> fix: screeningtool order

- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/usecases/appointments/appointment.go
> fix: exclude `PIN_RESET` when returning service requests

- .github/workflows/ci.yml
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
> feat: update appointments service request

- fixtures/clients_servicerequest.yml
- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/utils.go
- pkg/mycarehub/usecases/screeningtools/utils_test.go
> chore: add scores to screening tools

- fixtures/users_user.yml
- go.mod
- go.sum
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/enums/client_type.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- create user
- create identifier
- create client
> chore: client registration changes

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/usecases/user/user.go
> fix: patient service requests

- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: onboarding booleans

- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/services/fcm/mock/fcm_mock.go
- pkg/mycarehub/infrastructure/services/fcm/service.go
- pkg/mycarehub/infrastructure/services/fcm/service_unit_test.go
- pkg/mycarehub/infrastructure/services/fcm/validators.go
- pkg/mycarehub/infrastructure/services/fcm/validators_test.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: implement FCM push notifications

- fixtures/users_user.yml
- go.mod
- go.sum
- pkg/mycarehub/domain/notifications.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/helpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/notifications.graphql
- pkg/mycarehub/presentation/graph/notifications.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: list user notifications

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/usecases/notification/notification.go
> chore(deps): bump dependencies version

- fixtures/clients_healthdiaryentry.yml
- go.mod
- go.sum
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
> feat: get shared health diary entries

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> fix: screening tools order

- .pre-commit-config.yaml
- browser_detect/main.py
- pkg/mycarehub/infrastructure/services/fcm/service.go
> chore: add a pre-commit hook

- fixtures/clients_servicerequest.yml
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/screeningtools.graphql
- pkg/mycarehub/presentation/graph/screeningtools.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
> feat: get client screening tool responses

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/enums/feedback_type.go
- pkg/mycarehub/application/enums/feedback_type_test,go
- pkg/mycarehub/application/utils/feedback_email_template.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/feedback/feedback.go
- pkg/mycarehub/usecases/feedback/feedback_test.go
> refactor: refactor send feedback api

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> chore: add screening tool request count

- fixtures/staff_servicerequest.yml
- fixtures/staff_staff.yml
- fixtures/users_user.yml
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/domain/authority.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/appointments/appointment_test.go
- pkg/mycarehub/usecases/authority/mock/authority_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: add pin service request check for staff

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
> chore: return empty list when there is no new health diary entries

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
When an error is encountered while creating a patient, we should not
fail and return early.
> fix: accumulate errors when creating patient

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
> refactor: refactor shared health diary entries

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
> refactor: allow sharing of the entire health diary entry

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: get client profile

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
> fix: shared at time should only show when the client has chosen to report to staff

- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/appointments/appointment_test.go
- pkg/mycarehub/usecases/user/user.go
-  Accumulate error when creating multiple appointments
-  Username formatting
> chore: minor fixes

- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
> chore: update consumer invite message copy

- pkg/mycarehub/application/enums/notification_types.go
- pkg/mycarehub/application/enums/notification_types_test.go
- pkg/mycarehub/domain/notifications.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/notification/mock/mock.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/notification/notification_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
assorted fixes:
- add notification types
- created at field in notification
- ignore appointments in vital signs
- patients without a patient id
> feat: add facility/staff notifications

- fixtures/authority_authorityrole_users.yml
- fixtures/staff_staff.yml
- fixtures/users_user.yml
- pkg/mycarehub/domain/screeningtools.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
> chore: add client contact in service request

- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
> chore: remove profile update enum

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: add facility name in login payload

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: change registration payload to pick a single client type

- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/usecases/communities/communities.go
> fix: search community member

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/notifications.graphql
- pkg/mycarehub/presentation/graph/notifications.resolvers.go
- pkg/mycarehub/usecases/notification/mock/mock.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/notification/notification_test.go
This API will be used to check whether push notifications are being sent to the mobile app.
> feat: implement send notification(FCM) api

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/appointments/appointment_test.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/notification/messages.go
- pkg/mycarehub/usecases/notification/messages_test.go
- pkg/mycarehub/usecases/notification/notification.go
> feat: client notifications

- .github/workflows/deployment.yaml
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
> fix: query users add user id filter

- fixtures/common_notification.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/notifications.graphql
- pkg/mycarehub/presentation/graph/notifications.resolvers.go
- pkg/mycarehub/usecases/notification/mock/mock.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/notification/notification_test.go
> feat: mark notification as read

- .github/workflows/deployment.yaml
- fixtures/common_usersurveys.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat: get user surveys

- pkg/mycarehub/application/enums/user_type.go
- pkg/mycarehub/infrastructure/services/pubsub/helper.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
This will be used to send notifications to the Professional app. The events that have been added
include
-  When a message is flagged
-  When a member is added to a community
-  When a member is removed from a community
-  When a member is banned/unbanned
- Any new …
> feat: consume more Stream events

- gqlgen.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/enums/metrics.go
- pkg/mycarehub/application/enums/metrics_test.go
- pkg/mycarehub/domain/metrics.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/metrics.graphql
- pkg/mycarehub/presentation/graph/metrics.resolvers.go
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/metrics.go/metrics.go
- pkg/mycarehub/usecases/metrics.go/metrics_test.go
- pkg/mycarehub/usecases/usecases.go
> feat: metrics collection mutation

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/getstream/config_test.go
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/appointments/appointment_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- remove redundant appointment methods
> chore: restore reschedule appointment notification

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- pkg/mycarehub/usecases/otp/otp.go
This feature will automatically fill in the OTP messages sent to a phonenumber. It removes the
need of a user manually going to the messages to fetch the sent verification code
Docs: https://developers.google.com/identity/sms-retriever/request
- Any new files are …
> feat: add myCareHub `appIdentifier` to OTP verification messages

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
> fix: add service request message to red flags

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/enums/notification_types.go
- pkg/mycarehub/application/enums/user_role_types.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/authority/authority_test.go
- pkg/mycarehub/usecases/notification/messages.go
> chore: notify user when assigned roles

- .github/workflows/ci.yml
- pkg/mycarehub/application/common/helpers/mock/helpers_mock.go
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/surveys/mock/surveys_mock.go
- pkg/mycarehub/infrastructure/services/surveys/surveys.go
- pkg/mycarehub/infrastructure/services/surveys/surveys_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat: update user survey data after filing survey

- .github/workflows/ci.yml
- .github/workflows/deployment.yaml
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
Adding a feature where all records linked to a user are deleted
> refactor: tweak purge user functionality

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> chore: get active security questions

- deps.yaml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/infrastructure/services/clinical/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/clinical/service.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: remove fhir records when deleting a client

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
This PR introduces a tweak where staff users can now be searched using either their
phonenumber, staff number or username
> chore: search staff members using more parameters

- pkg/mycarehub/infrastructure/services/pubsub/subscriber_test.go
- tests/config_test.go
> test: add pubsub subscriber tests

- .github/workflows/ci.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> fix: fetch notifications in a descending order

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/helper.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber_test.go
- pkg/mycarehub/usecases/notification/messages.go
- pkg/mycarehub/usecases/notification/messages_test.go
> chore: minor app fixes

- .github/workflows/ci.yml
- go.mod
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
> chore: remove database logic from usecase layer

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> fix: missing query param on get screening tools

- pkg/mycarehub/usecases/user/login.go
> chore: add stream user extra data on upsert

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: transfer client to facility

- go.mod
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/user/login.go
> chore: upsert getstream user

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
Added the following changes
-  Delete user metrics when purging the user
-  Search client using the phonenumber, username or ccc number
> fix: assorted app fixes

- pkg/mycarehub/infrastructure/services/getstream/mock/stream_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/infrastructure/services/getstream/stream_test.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> fix: list community members

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
> fix: fix sharing health diary

- pkg/mycarehub/usecases/communities/communities.go
> fix: update channel fields used to filter query results

- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/domain/login.go
- pkg/mycarehub/infrastructure/services/clinical/service_test.go
> chore: clinical tests, omit user in login response

- pkg/mycarehub/application/common/helpers/mock/helpers_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chores: assorted chores

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/services/surveys/mock/surveys_mock.go
- pkg/mycarehub/infrastructure/services/surveys/surveys.go
- pkg/mycarehub/infrastructure/services/surveys/surveys_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/notification/messages.go
- pkg/mycarehub/usecases/notification/messages_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat: validate an existing survey when sending out surveys

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
> fix: check empty slice when creating surveys

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> chore: query facilities using the mflcode or facility name

- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> chore: allow list of actions when resolving service request

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/facility/facility.go
> chore: return facilities in ascending order

- pkg/mycarehub/infrastructure/services/getstream/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/getstream/stream.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
> fix: sort community members

- .github/workflows/ci.yml
- fixtures/clients_healthdiaryquote.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
> chore: fetch a list of random health diary quotes

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
> chore: get health diary entries by different filters

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> feat: search service request by username or phonenumber and request type

- .github/workflows/demo.yaml
> ci: deploy demo environment

- .github/workflows/demo.yaml
- .github/workflows/staging.yaml
- deps.yaml
> chore: add clinical demo to deps.yaml

- fixtures/clients_servicerequest.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> chore: include facility id when searching service requests

- .github/workflows/demo.yaml
> ci: push schema to demo schema registry

- fixtures/clients_identifier.yml
- fixtures/common_contact.yml
- fixtures/staff_staff.yml
- fixtures/staff_staff_identifiers.yml
- fixtures/users_user.yml
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: remove django api when registering staff

- .github/workflows/demo.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
- go.mod
- go.sum
> feat: add migration step during deployment

- .github/workflows/testing.yaml
> ci: fix testing deployment

- db/migrations/000003_create_questionnaire.down.sql
- db/migrations/000003_create_questionnaire.up.sql
> chore: setup questionnaire schema

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> fix: return staff contact

- fixtures/questionnaires_questioninputchoice.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/domain/questionnaires_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> feat: respond to screeningtool questionnaire

- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/usecases/questionnaires/mock/questionnaires_mock.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> feat: get available screening tools

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> feat: get screening tool by id

- fixtures/common_usersurveys.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> fix: survey sending logic

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> fix: get available surveys

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- fixtures/appointments_appointment.yml
- fixtures/clients_servicerequest.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- tests/config_fixtures.go
- tests/config_test.go
- tests/kenya_emr_acceptance_test.go
> test: setup acceptance tests

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> fix: survey notifications

- tests/service_requests_acceptance_test.go
> test: service request acceptance tests

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> feat: list responded screening tools for a facility

- db/migrations/000005_alter_common_usersurveys.down.sql
- db/migrations/000005_alter_common_usersurveys.up.sql
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat: get survey respodents

- go.mod
- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/services/surveys/mock/surveys_mock.go
- pkg/mycarehub/infrastructure/services/surveys/surveys.go
- pkg/mycarehub/infrastructure/services/surveys/surveys_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/notifications.graphql
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/submission.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat:user survey submissions

- fixtures/clients_servicerequest.yml
- fixtures/questionnaires_screeningtoolquestionresponse.yml
- fixtures/questionnaires_screeningtoolresponse.yml
- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/screeningtools/screeningtools_test.go
- tests/config_fixtures.go
> feat: get screeningtool respondents

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/surveys/submission.go
> fix: fix surveys

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: register staff in transaction

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/usecases/user/user.go
> chore: register client in a transaction

- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/user/user.go
- tests/kenya_emr_acceptance_test.go
> test: wire up kenya emr acceptance tests

- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> chore: assorted screening tool chores

- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/infrastructure/services/clinical/service.go
- pkg/mycarehub/infrastructure/services/clinical/service_test.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber_test.go
- pkg/mycarehub/infrastructure/services/surveys/surveys.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/facility_acceptance_test.go
- tests/service_requests_acceptance_test.go
> chore: retire deprecated ``ioutil`` and replace with ``io``

- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> chore: paginate facility responded screening tools response

- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/domain/questionnaires_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> feat: get screening tool response

- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> chore: paginate screening tool respondents

- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
- pkg/mycarehub/usecases/otp/otp.go
> chore: update app name

- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/mock/surveys_mock.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat: fetch surveys with service requests in a given facility

- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/mock/surveys_mock.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> feat: get users with survey service requests

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> chore: assorted search user chores

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/dto/pubsub.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/services/cms/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/cms/service.go
- pkg/mycarehub/infrastructure/services/cms/service_test.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: cms client subscriber

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/dto/pubsub.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/services/cms/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/cms/service.go
- pkg/mycarehub/infrastructure/services/cms/service_test.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: create cms service user via pub sub

- .github/workflows/ci.yml
- .github/workflows/demo.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
- pkg/mycarehub/usecases/otp/otp.go
> chore: set demo environment invitation and otp messages

- .github/workflows/demo.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
> fix: ci missing `=` in key-value pair

- db/migrations/000006_alter_client.down.sql
- db/migrations/000006_alter_client.up.sql
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: switch facility

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: create cms staff via pubsub

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
> chore: append facilities on staff and client registration

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/usecases/user/user.go
> fix: show error when user selects invalid facility

- fixtures/common_facility.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/config_fixtures.go
> feat: add facilities to staff profile

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
This PR introduces a feature where we are able to list all the facilities where a user (client or HCW) is a member
> feat: list a user's linked facilities

- fixtures/clients_client_facilities.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: add facilities to client profile

- fixtures/common_notification.yml
- pkg/mycarehub/domain/workstation_detail.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
> feat: fetch user's notification count

- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/dto/workstation_detail.go
- pkg/mycarehub/domain/facility.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: paginate user linked facilities

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> feat: get staff service request count

- .github/workflows/staging-multitenant.yaml
> feat(ci): deploy multitenant-staging environment

- fixtures/caregivers_caregiver.yml
- fixtures/caregivers_caregiver_client.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- search caregiver by username, phone and caregiver number
> feat: search caregiver

- fixtures/clients_client_facilities.yml
- fixtures/common_facility.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/config_fixtures.go
> feat: remove assigned facilities from client profile

- fixtures/caregivers_caregiver.yml
- fixtures/caregivers_caregiver_client.yml
- fixtures/clients_caregiver.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/config_fixtures.go
> feat: add caregiver to client

- .golangci.yaml
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/domain/login.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/login.go
- pkg/mycarehub/usecases/user/login_test.go
- pkg/mycarehub/usecases/user/user.go
> feat: handle caregiver login

- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: remove assigned facilities from staff profile

- .github/workflows/staging-multitenant.yaml
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: send caregiver invite

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: register a client as a caregiver

- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: list caregiver's clients

- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- the api returns a list of all caregivers assiged to a certain client
> feat: list clients caregivers

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- marks the client as having consented to being assigned a certain caregiver
> feat: client consent

- pkg/mycarehub/usecases/communities/communities.go
> fix: repace null return with empty list in recomended communities

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- marks a caregiver as having consented to be assigned to a client
> feat: caregiver consent

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> chore: assorted chores

- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> feat: get work station items count (surveys, notifications)

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: caregiver assorted fixes

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: client assignment in caregiver registration

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: assorted chores (#588)

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> chore: assorted search chores

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> chore: search assorted chores

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
- pkg/mycarehub/usecases/screeningtools/screeningtools.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: return `DefaultFacility` object rather than `DefaultFacilityID` and `DefaultFacilityName`

- pkg/mycarehub/usecases/communities/communities.go
> fix: recommended communities filters

- pkg/mycarehub/domain/login.go
> fix: change caregiver client login response

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/demo.yaml
- .github/workflows/gitguardian.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging-multitenant.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
- go.mod
- go.sum
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/services/sms/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/sms/mock/sms_mock.go
- pkg/mycarehub/infrastructure/services/sms/sms.go
- pkg/mycarehub/infrastructure/services/sms/sms_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/user/login_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: tranfer sending of SMS to SIL Comms library

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: resolved by name for resolved service requests

- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
> fix: client opt out

- fixtures/common_facility.yml
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/scope.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/middleware.go
- tests/config_test.go
- tests/facility_acceptance_test.go
> feat: add organisation middleware, use organisation id in queries

- db/migrations/000005_alter_common_usersurveys.up.sql
- db/migrations/000007_alter_table_common_feeback.up.sql
> fix: schema evolution for user surveys

- db/migrations/000007_alter_table_common_feeback.down.sql
- db/migrations/000007_alter_table_common_feeback.up.sql
- db/migrations/000008_alter_common_feedback_nulls.down.sql
- db/migrations/000008_alter_common_feedback_nulls.up.sql
> fix: drop common feedback constraint migrations

- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/scope.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
> chore: fix implicit organisation database query methods

- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/graph/appointments.resolvers.go
- pkg/mycarehub/presentation/graph/authority.resolvers.go
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/feedback.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/presentation/graph/metrics.resolvers.go
- pkg/mycarehub/presentation/graph/notifications.resolvers.go
- pkg/mycarehub/presentation/graph/otp.resolvers.go
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/presentation/graph/screeningtools.resolvers.go
- pkg/mycarehub/presentation/graph/securityquestion.resolvers.go
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
> chore: add field to indicate whether caregiver is also a client

- .github/workflows/ci.yml
- .github/workflows/demo.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
- go.mod
- go.sum
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/services/sms/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/sms/mock/sms_mock.go
- pkg/mycarehub/infrastructure/services/sms/sms.go
- pkg/mycarehub/infrastructure/services/sms/sms_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: move sms sending to SIL Comms

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
> feat: link a health diary entry to a service request

- db/migrations/000009_alter_caregivers_caregiver_client.down.sql
- db/migrations/000009_alter_caregivers_caregiver_client.up.sql
- fixtures/caregivers_caregiver_client.yml
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/enums/consent_states.go
- pkg/mycarehub/application/enums/consent_type_test.go
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- remove unnecessary output model field
> refactor: list client caregiver output

- go.mod
- go.sum
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/external_test.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/infrastructure/services/mail/mock/mail_mock.go
- pkg/mycarehub/infrastructure/services/mail/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/mail/service.go
- pkg/mycarehub/infrastructure/services/mail/service_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/feedback/feedback.go
- pkg/mycarehub/usecases/feedback/feedback_test.go
- Aim is to clean up the service by removing unnecessary depedency on engagement which clutter our env vars
> refactor: move sending email logic to mycarehub - v1

- go.mod
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/external_test.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- Aim: eliminate over-reliance on engagement
- Get rid of unwanted env vars from engagement
- Any new files are updated in the folder structure in the …
> refactor: move otp related logic from login to mycarehub - v2

- go.mod
- go.sum
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/extension/external.go
- pkg/mycarehub/application/extension/external_test.go
- pkg/mycarehub/application/extension/mock/extension_mock.go
- pkg/mycarehub/infrastructure/services/mail/mock/mail_mock.go
- pkg/mycarehub/infrastructure/services/mail/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/mail/service.go
- pkg/mycarehub/infrastructure/services/mail/service_test.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/feedback/feedback.go
- pkg/mycarehub/usecases/feedback/feedback_test.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- Aim is to clean up the service by removing unnecessary depedency on engagement which clutter our env vars
- Any new files are updated in the folder …
> refactor: move sending email logic to mycarehub - v2

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> fix: organization joins

- db/migrations/000001_initial.down.sql
- db/migrations/000001_initial.up.sql
> chore: setup initial migrations

- db/migrations/000001_initial.down.sql
- db/migrations/000001_initial.up.sql
> chore: add foreign key constraint names

- .github/workflows/ci.yml
- .github/workflows/staging-multitenant.yaml
- fixtures/clients_client.yml
- fixtures/common_program.yml
- fixtures/common_program_facility.yml
- fixtures/common_program_user.yml
- fixtures/users_user.yml
- go.mod
- go.sum
- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- tests/config_fixtures.go
- This is complementary to initial migration 000001
> chore: add program id to database model objects

- db/migrations/000002_alter_organisation.down.sql
- db/migrations/000002_alter_organisation.up.sql
- fixtures/common_organisation.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/models.go
- pkg/mycarehub/domain/organisation.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/organisation.graphql
- pkg/mycarehub/presentation/graph/organisation.resolvers.go
- pkg/mycarehub/usecases/organisation/mock/organisation_mock.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- pkg/mycarehub/usecases/usecases.go
- the API is used whenever there is need to create a new organisation"
> feat: create organisation

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete.go
- pkg/mycarehub/infrastructure/database/postgres/pg_delete_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/organisation.graphql
- pkg/mycarehub/presentation/graph/organisation.resolvers.go
- pkg/mycarehub/usecases/organisation/mock/organisation_mock.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- pkg/mycarehub/usecases/usecases.go
- API to be used by when managers may have a need to delete an organisation
> feat: delete an organisation

- go.mod
- go.sum
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/delete_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mappers_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: fix user (staff and client) registration

- fixtures/common_program_user.yml
- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/config_fixtures.go
- tests/programs_acceptance_test.go
fix:
- listing user linked organisations
> feat: program selection, setting current program

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/login.go
- pkg/mycarehub/usecases/user/login_test.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: login by username and pin

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> fix: fetch survey responses within a staff facility

- .github/workflows/ci.yml
- go.mod
- go.sum
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/organisation/mock/organisation_mock.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- Used to list the organisations registered in the platform.
- Used to provide organisation to login in with.
> feat: list organizations

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.resolvers.go
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/user/login.go
- pkg/mycarehub/usecases/user/login_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: gorm test

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- pkg/mycarehub/usecases/user/login_test.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: list user programs

- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- tests/programs_acceptance_test.go
> fix: restore list user programs

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/user/user.go
> fix: register client

- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- Fixes failing client registration after a db model changes
> fix: caregiver registration

- fixtures/common_program_facility.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
> feat: get program facilities

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
- tests/staff_acceptance_test.go
> ref: set current facility

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_unit_test.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/notification/notification_test.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
- pkg/mycarehub/usecases/user/login.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/config_test.go
- tests/programs_acceptance_test.go
- API is used to set client's and staff's current program and organisation IDs during logins
> feat: set client and staff program

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
> fix: retry otp

- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
> fix: failing tests

- db/migrations/000002_add_current_client_and_facility.down.sql
- db/migrations/000002_add_current_client_and_facility.up.sql
- fixtures/caregivers_caregiver.yml
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/caregiver_acceptance_test.go
> chore: add current client and facility

- fixtures/users_user.yml
- fixtures/users_userpin.yml
- pkg/mycarehub/application/dto/login.go
- pkg/mycarehub/usecases/user/login.go
> chore: restore login boolean responses

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
> feat: register existing user as a client

- db/migrations/000003_add_unique_together_for_user_organisation_in_caregiver.down.sql
- db/migrations/000003_add_unique_together_for_user_organisation_in_caregiver.up.sql
- fixtures/caregivers_caregiver.yml
- fixtures/caregivers_caregiver_client.yml
- fixtures/clients_client.yml
- fixtures/common_organisation.yml
- fixtures/users_user.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/caregiver_acceptance_test.go
- tests/config_fixtures.go
> feat: set current client on caregiver profile

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
- tests/staff_acceptance_test.go
- feature used on instances where there is need to create a staff for an already existing user in a certain program
> feat: register existing user as staff

- pkg/mycarehub/application/common/testutils/testhelpers.go
- pkg/mycarehub/domain/authority.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
> chore: update set staff program response

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
- include:
- get stream token
- roles and permissions
> refactor: set client program

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/caregiver_acceptance_test.go
> feat: set caregiver's current facility

- go.mod
- go.sum
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
- API used to create a create a client for an already existing user to whom there may be a need to create a caregiver profile.
- User can only have one caregiver profile in a certain organisation
- Any …
> feat: create caregiver profile for an existing user

- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
> fix: restore has set nickname boolean

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> fix: get managed clients

- go.mod
- go.sum
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/otp.graphql
- pkg/mycarehub/presentation/graph/otp.resolvers.go
- tests/config_fixtures.go
- tests/otp_acceptance_test.go
- update graphql query arguements
- add acceptance test
> chore: send otp

- .github/workflows/ci.yml
- .github/workflows/demo.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging-multitenant.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/appointments.go
- pkg/mycarehub/domain/caregiver.go
- pkg/mycarehub/domain/facility.go
- pkg/mycarehub/domain/notifications.go
- pkg/mycarehub/domain/organisation.go
- pkg/mycarehub/domain/security_questions.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/domain/terms.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- tests/caregiver_acceptance_test.go
- tests/client_acceptance_test.go
- tests/facility_acceptance_test.go
- tests/programs_acceptance_test.go
- tests/security_questions_acceptance_test.go
- tests/service_requests_acceptance_test.go
- tests/staff_acceptance_test.go
- ensure use of camel case in graph inputs and responses
> chore: camelcase graphql args and types

- .github/workflows/prod.yaml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/staff_acceptance_test.go
- API is used to update clients information. This includes phone number, username and client's CCC number
> feat: update user profile

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- tests/organisation_acceptance_test.go
> feat: create cms organisation via pubsub

- pkg/mycarehub/domain/otp.go
- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/otp.graphql
- pkg/mycarehub/presentation/graph/otp.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/otp_acceptance_test.go
> refactor: return phone number when sending OTP

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/content/content.go
> feat: create cms facility via pubsub

- pkg/mycarehub/domain/feedback.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/feedback/feedback.go
> fix: send feedback

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- when a facility is added to any program in mycarehub, update the respective records in the CMS via pubsub
> feat: link facility to program pubsub

- pkg/mycarehub/application/enums/client_identifier_type.go
- pkg/mycarehub/application/enums/client_identifier_type_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
> feat: check client identifier exists

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- tests/facility_acceptance_test.go
> fix: populate facility identifier

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/surveys.go
> fix: populate survey fields

- go.mod
- go.sum
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/organisation.graphql
- pkg/mycarehub/presentation/graph/organisation.resolvers.go
- pkg/mycarehub/usecases/organisation/mock/organisation_mock.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- tests/organisation_acceptance_test.go
- searches an organisation in the platform using either the name or business registration number
> feat: search organisation

- go.mod
- go.sum
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
- used to search for the programs in the organisation of the currently logged in user
> feat: search program(s)

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
- retrieves a paginated list of programs that belong to the organisation of the currently logged in user
> feat: list programs

- db/migrations/000006_add_program_description.down.sql
- db/migrations/000006_add_program_description.up.sql
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/program.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
- the api retrieved a program and outputs its details
Extras:
- added `description` column in the program db model
> feat: get program by id

- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/organisation.graphql
- pkg/mycarehub/presentation/graph/organisation.resolvers.go
- pkg/mycarehub/usecases/organisation/mock/organisation_mock.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- tests/organisation_acceptance_test.go
> feat: create organisation with programs

- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
> chore: publish cms facilities

- Dockerfile
> fix: golang docker version

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
> fix: create program

- fixtures/common_contact.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- remove get or create when creating contact since contact can be shared
> fix: client and staff registration

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: create superuser

- db/migrations/000007_add_user_email_field.down.sql
- db/migrations/000007_add_user_email_field.up.sql
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
> chore: add email to user profile

- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
> fix: correct cms api

- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
> fix: create health diary

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> chore: append programs when listing organisations

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: update user email

- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
> fix: screening tools v2

- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> chore: publish facilities to clinical service and CMS

- db/migrations/000008_update_authorization_tables.down.sql
- db/migrations/000008_update_authorization_tables.up.sql
- fixtures/authority_authoritypermission.yml
- fixtures/authority_authorityrole.yml
- fixtures/authority_authorityrole_permissions.yml
- fixtures/authority_authorityrole_users.yml
- pkg/mycarehub/domain/authority.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- tests/config_fixtures.go
> chore: update authority tables

- pkg/mycarehub/authorization/permissions.go
- pkg/mycarehub/authorization/permissions_test.go
- pkg/mycarehub/authorization/roles.go
- pkg/mycarehub/authorization/roles_test.go
- pkg/mycarehub/domain/authority.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/usecases/authority/authority.go
- pkg/mycarehub/usecases/authority/mock/authority_mock.go
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
> chore: setup system permissions

- db/migrations/000011_add_current_user_type.down.sql
- db/migrations/000011_add_current_user_type.up.sql
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/user/user.go
> chore: set current user type

- pkg/mycarehub/application/utils/data/mycarehub_program_screeningtools.json
- pkg/mycarehub/application/utils/json.go
- pkg/mycarehub/application/utils/json_test.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
> chore: load screening tools on program creation

- fixtures/users_user.yml
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/services/matrix/matrix.go
- pkg/mycarehub/infrastructure/services/matrix/matrix_test.go
- pkg/mycarehub/infrastructure/services/matrix/mock/matrix_mock.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/user/login_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/community_acceptance_test.go
- tests/config_test.go
- tests/otp_acceptance_test.go
- wire/provider.go
- create matrix user when registering mch clients, staffs and caregivers
> feat: register matrix user

- fixtures/communities_community.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/communities/mock/community_mock.go
- tests/community_acceptance_test.go
- API used to support multitenancy such that a user can only see rooms in the programs that he/she is logged in into.
> feat: list rooms

- pkg/mycarehub/infrastructure/services/surveys/surveys.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
> fix: health diary service requests duplication

- .github/workflows/demo.yaml
- .github/workflows/prod.yaml
- .github/workflows/staging.yaml
- .github/workflows/testing.yaml
> chore: ci-cd assorted chores

- pkg/mycarehub/infrastructure/services/matrix/matrix.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/community_acceptance_test.go
- tests/config_test.go
- wire/provider.go
> fix: add community token when setting client or staff program

- data/securityquestions.json
- pkg/mycarehub/domain/security_questions.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/cmd/commands.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/cmd/service/testData/securityquestions/invalidFlavour.json
- pkg/mycarehub/presentation/cmd/service/testData/securityquestions/invalidResponseType.json
- pkg/mycarehub/presentation/cmd/service/testData/securityquestions/valid.json
- pkg/mycarehub/usecases/securityquestions/mock/security_questions_mock.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
> chore: load security questions cli

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> chore: register superuser in matrix

- pkg/mycarehub/application/utils/loggedin_user.go
- pkg/mycarehub/application/utils/loggedin_user_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
> chore: restore created by and updated by

- pkg/mycarehub/application/dto/input.go
> chore: fix screening tool question tag

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
> feat: check if phone exists

- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/usecases/organisation/organisation.go
- tests/organisation_acceptance_test.go
> chore: update create organisation

- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/programs_acceptance_test.go
> chore: update add facility to program

- pkg/mycarehub/domain/notifications.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/notification/notification.go
> fix: send surveys

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
> fix: create pin reset service request

- fixtures/clients_client.yml
- fixtures/users_user.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- tests/caregiver_acceptance_test.go
- tests/config_fixtures.go
> chore: test assign caregiver

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/appointments/appointment.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/surveys/surveys.go
> fix: service requests

- pkg/mycarehub/application/enums/servicerequest_status.go
- pkg/mycarehub/application/enums/servicerequest_status_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- tests/client_acceptance_test.go
- tests/staff_acceptance_test.go
> fix: pin reset service request verification

- fixtures/common_program_facility.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
> fix: facility data partitioning

- fixtures/common_usersurveys.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
- tests/survey_acceptance_test.go
> fix: survey form data partitioning

- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/services/matrix/matrix.go
- pkg/mycarehub/infrastructure/services/matrix/mock/matrix_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
- Returns community profile when a client/staff selects thei program. This will be usefed by FE to handle chats display.
> chore: return community profile

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/notification/notification_test.go
> chore: add program id when fetching notification filters

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- allows searching of staff member by their name
> chore: search staff by name

- pkg/mycarehub/application/common/helpers/helpers.go
- pkg/mycarehub/application/common/helpers/helpers_test.go
> chore: send username when sending invite sms

- .gitguardian.yaml
- fixtures/oauth_authorization_code.yml
- fixtures/oauth_client.yml
- fixtures/oauth_session.yml
- fixtures/users_user.yml
- pkg/mycarehub/domain/oauth.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/update_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/oauth/authorization_code.go
- tests/config_fixtures.go
> feat: fosite authorization code implementation

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
> chore: allow search client and caregiver by name

- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/services/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/form.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> fix: list surveys

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/staff_acceptance_test.go
> fix: create organisation admin

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
> fix: get survey with service request

- go.mod
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/services/matrix/matrix.go
- pkg/mycarehub/infrastructure/services/matrix/matrix_test.go
- pkg/mycarehub/infrastructure/services/matrix/mock/matrix_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- The API will be used to deactivate community users once a user has opted out from MyCareHub
- For more details, check this out: [https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html#deactivate-account}
Other accompanying chores:
- Enforce lowecase when saving usernames This minimizes trouble with Matrix which only allows alphanumeric usernames with no caps
- Fix opt-out bug. The API will now use `username` and NOT `phoneNumber` since phone number is a shared entity
- Few clean-up chores
[![Tests](https://img.shields.io/badge/Tests-0-success.svg?style=for-the-badge)]( …
> feat: deactivate community user

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> fix: staff profile details

- .github/workflows/ci.yml
- .github/workflows/staging-multitenant.yaml
- .gitignore
- go.mod
- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/oauth_session.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/mappers.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/html/html.go
- pkg/mycarehub/presentation/rest/html/layout.html
- pkg/mycarehub/presentation/rest/html/login.html
- pkg/mycarehub/presentation/rest/oauth.go
- pkg/mycarehub/usecases/oauth/client.go
- pkg/mycarehub/usecases/oauth/fosite.go
- pkg/mycarehub/usecases/oauth/mock/oauth_mock.go
- pkg/mycarehub/usecases/oauth/oauth.go
> feat: oauth handlers

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/rest/oauth.go
> chore: add extra session details

- .github/workflows/demo.yaml
- .github/workflows/testing.yaml
> feat(ci): deploy demo environment to k8s

- .github/workflows/demo.yaml
- .github/workflows/staging.yaml
> feat(ci): deploy `staging` environment to k8s

- pkg/mycarehub/infrastructure/services/pubsub/service.go
> chore: change topic version to v2

- .github/workflows/prod.yaml
> feat(ci): deploy prod environment to k8s

- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/staff_acceptance_test.go
> chore: remove staff registration pubsub

- go.mod
- go.sum
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/html/facility_chooser.html
- pkg/mycarehub/presentation/rest/html/html.go
- pkg/mycarehub/presentation/rest/html/layout.html
- pkg/mycarehub/presentation/rest/html/program_chooser.html
- pkg/mycarehub/presentation/rest/mock/oauth2_mock.go
- pkg/mycarehub/presentation/rest/mock/sessionmanager_mock.go
- pkg/mycarehub/presentation/rest/oauth.go
- pkg/mycarehub/presentation/rest/oauth_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: add session cookies

- pkg/mycarehub/usecases/user/login.go
> fix: getstream username

- fixtures/common_securityquestion.yml
- fixtures/common_securityquestionresponse.yml
- fixtures/users_user.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/rest/handlers_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/config_fixtures.go
> fix: get responded security questions

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/otp/mock/otp_mock.go
- pkg/mycarehub/usecases/otp/otp.go
- pkg/mycarehub/usecases/otp/otp_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/staff_acceptance_test.go
> fix: get user data

- pkg/mycarehub/usecases/surveys/submission.go
> fix: multi-choice survey response

- pkg/mycarehub/presentation/rest/html/layout.html
- pkg/mycarehub/presentation/rest/html/login.html
- pkg/mycarehub/presentation/rest/oauth.go
- pkg/mycarehub/presentation/rest/oauth_test.go
> chore: add error message in login template

- pkg/mycarehub/presentation/rest/oauth.go
> fix: oauth extra data

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> fix: send user survey

- fixtures/clients_servicerequest.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/surveys/surveys.go
> fix: skip clients with service requests when sending surveys

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
> fix: create health diary entry note

- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/user/user.go
> fix: register facility patients

- pkg/mycarehub/domain/appointments.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/appointments/appointment.go
> fix: create appointments

- README.md
- pkg/mycarehub/application/common/constants.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/services/matrix/mock/matrix_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher.go
- pkg/mycarehub/infrastructure/services/pubsub/publisher_test.go
- pkg/mycarehub/infrastructure/services/pubsub/service.go
- pkg/mycarehub/infrastructure/services/pubsub/service_test.go
- pkg/mycarehub/infrastructure/services/pubsub/subscriber.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- wire/provider.go
- intention is to have the matrix user registration happen later incase matrix was down for some reason during user regitration
> chore: register matrix user via pubsub

- db/migrations/000008_update_authorization_tables.down.sql
- db/migrations/000017_add_organisation_admin_field.down.sql
- db/migrations/000017_add_organisation_admin_field.up.sql
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/staff_acceptance_test.go
> feat: update organisation admin permissions

- fixtures/caregivers_caregiver_client.yml
- fixtures/clients_client.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/user.graphql
- pkg/mycarehub/presentation/graph/user.resolvers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
- tests/config_fixtures.go
- use enums instead of booleans for consent to accept or revoke consent
> fix: consent update

- .github/workflows/ci.yml
- .github/workflows/staging-multitenant.yaml
> feat(ci): add pipeline to deploy mycarehub SIL copy

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: list caregiver id mapping

- fixtures/users_user.yml
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: publish client to cms

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: set current user type

- db/migrations/000018_update-client-caregiver-schemas.down.sql
- db/migrations/000018_update-client-caregiver-schemas.up.sql
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
> chore: update caregiver client models

- .github/workflows/staging-multitenant.yaml
> chore: use matrix strategy to create multiple job runs

- .github/workflows/ci.yml
- .github/workflows/multitenant-deploy.yaml
- browser_detect/requirements.txt
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/healthdiary.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/healthdiary.graphql
- pkg/mycarehub/presentation/graph/healthdiary.resolvers.go
- pkg/mycarehub/usecases/healthdiary/healthdiary.go
- pkg/mycarehub/usecases/healthdiary/healthdiary_test.go
- pkg/mycarehub/usecases/healthdiary/mock/mock.go
- tests/healthdiary_acceptance_test.go
> feat: record health diary entry for a client as a caregiver

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/questionnaires.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- tests/questionnaire_acceptance_test.go
> feat: record assessment tool on behalf of the client

- fixtures/users_user.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/communities/mock/community_mock.go
- pkg/mycarehub/usecases/notification/notification.go
- tests/config_fixtures.go
- tests/kenya_emr_acceptance_test.go
- wire/provider.go
- matrix pusher uses this endpoint to send notification events to our mch backend which serves as the push gateway for Matrix's notification events.
> feat: mycarehub-matrix push gateway

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/user/user.go
- tests/caregiver_acceptance_test.go
- allow HCW to state the consent state of a caregiver when assigning them to a client
> chore: require caregiver consent when assigning caregiver to a client

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
- the API can retrive all programs when no search criteria is provided
- search and show a list of facilities that match the search term provided
Additionals:
- add pagination to search program(s) API
- Any new files are updated in the folder structure in the …
> refactor: list program API

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/programs.graphql
- pkg/mycarehub/presentation/graph/programs.resolvers.go
- pkg/mycarehub/usecases/programs/mock/programs_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/programs_acceptance_test.go
Reverts savannahghi/mycarehub#860
> Revert "refactor: list program API"

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: return program description when retrieving programs

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- tests/service_requests_acceptance_test.go
> feat: create service request on behalf of the client

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/surveys.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/surveys/surveys.go
> feat: record survey on behalf of the client

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> feat: add caregiver information in service request

- pkg/mycarehub/domain/communities.go
- pkg/mycarehub/infrastructure/services/matrix/matrix.go
- pkg/mycarehub/infrastructure/services/matrix/matrix_test.go
- pkg/mycarehub/infrastructure/services/matrix/mock/matrix_mock.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- configures when the gateway should receive notification events in a room
> feat: set push rule

- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/usecases/notification/messages.go
- pkg/mycarehub/usecases/notification/notification.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- sending of push notifications
- inbox notification listing
> fix: notifications

- fixtures/common_identifiers.yml
- fixtures/staff_staff.yml
- fixtures/staff_staff_identifiers.yml
- fixtures/users_user.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/config_fixtures.go
- tests/staff_acceptance_test.go
> feat: add new program to staff profile

- pkg/mycarehub/presentation/graph/communities.graphql
- pkg/mycarehub/presentation/graph/communities.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/communities/communities.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/communities/mock/community_mock.go
- pkg/mycarehub/usecases/programs/programs.go
- pkg/mycarehub/usecases/programs/programs_test.go
- tests/caregiver_acceptance_test.go
- tests/client_acceptance_test.go
- tests/community_acceptance_test.go
- tests/staff_acceptance_test.go
> chore: decouple matrix on select program

- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/rest/oauth.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
> fix: list program facilities

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- tests/service_requests_acceptance_test.go
> refactor: fetch program's pending service requests count

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- retrieves service requests belonging to the current logged in user's program
> refactor: get service requests

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: program facility workstation details count

- fixtures/common_contact.yml
- fixtures/users_user.yml
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/pubsub/mock/service_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/caregiver_acceptance_test.go
- tests/client_acceptance_test.go
- tests/community_acceptance_test.go
- tests/config_test.go
- tests/otp_acceptance_test.go
- tests/staff_acceptance_test.go
> feat: add program to client profile

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: alert user via an SMS when they are added to a new facility

- pkg/mycarehub/presentation/middleware.go
> fix: fail fast when user ID is missing in the token info

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> feat: search staff profiles as a non-admin

- .gitignore
- fixtures/staff_staff.yml
- pkg/mycarehub/usecases/user/user.go
- tests/staff_acceptance_test.go
> fix: search staff as admin user

- .github/workflows/ci.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/client_acceptance_test.go
> feat: search client as a non admin user

- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/middleware.go
> feat: add middleware to store user organisation and program in context

- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/scope.go
> feat: add gorm scopes to re-use commonly used logic

- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/organisation.graphql
- pkg/mycarehub/presentation/graph/organisation.resolvers.go
- pkg/mycarehub/usecases/organisation/mock/organisation_mock.go
- pkg/mycarehub/usecases/organisation/organisation.go
- tests/organisation_acceptance_test.go
> fix: create organisation

- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/scope.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
The presence of whitespaces in the search parameter caused no records to be returned
> fix: trim whitespace on search param when searching for client

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
Phonenumbers are stored in the database with the country code i.e `+254711223344`. To ensure successful searching for Kenyan clients using the number format `0711223344`, we've made a thoughtful improvement by removing the first occurrence of '0' from the provided number. This allows us to efficiently search for the rest of the number using PostgreSQL's pattern matching capabilities, which seamlessly handles the remaining matching process. As a result, we can now find the correct records, enabling smoother and more accurate searches for Kenyan clients in the database 😉  …
> fix: search clients using phonenumbers without the country code

- pkg/mycarehub/usecases/content/content.go
- excludes content items belonging to consumer-faqs and pro-faqs by default
- ensures that faq(s) content is not shown in the app when retrieving contents but only when fetching faqs
- Any new files are updated in the folder structure in the …
> chore: filter content by query params

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> refactor: move set current usertype logic for clients

- pkg/mycarehub/usecases/otp/otp.go
> chore: append a message when sending retry otp to user

- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> fix: get health diary entry as caregiver

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/questionnaire.graphql
- pkg/mycarehub/presentation/graph/questionnaire.resolvers.go
- pkg/mycarehub/usecases/questionnaires/mock/questionnaires_mock.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
- tests/screeningtool_acceptance_test.go
> fix: get available sceeningtools as a caregiver

- pkg/mycarehub/presentation/graph/content.graphql
- pkg/mycarehub/presentation/graph/content.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/content/mock/content_mock.go
- tests/content_acceptance_test.go
> feat: view content as caregiver

- pkg/mycarehub/infrastructure/services/mail/service.go
> chore: source email from configuration

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/surveys.graphql
- pkg/mycarehub/presentation/graph/surveys.resolvers.go
- pkg/mycarehub/usecases/surveys/mock/surveys_mock.go
- pkg/mycarehub/usecases/surveys/surveys.go
- pkg/mycarehub/usecases/surveys/surveys_test.go
- tests/survey_acceptance_test.go
> feat: get surveys on behalf of client

- data/facilities.csv
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/application/utils/csv.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd_test.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
> feat: create facilities

- fixtures/clients_client_identifiers.yml
- fixtures/common_identifiers.yml
- pkg/mycarehub/domain/user.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_update_unit_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> fix: client output

- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
> fix: kenyaemr get service request

- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
> fix: send invite SMS to international phone numbers

- pkg/mycarehub/usecases/user/user.go
> chore: set consent when registering caregiver with assigned clients

- pkg/mycarehub/application/exceptions/custom_errors.go
- pkg/mycarehub/application/exceptions/error_codes.go
- pkg/mycarehub/application/exceptions/error_messages.go
- pkg/mycarehub/application/exceptions/exceptions_test.go
- pkg/mycarehub/usecases/organisation/organisation.go
- pkg/mycarehub/usecases/organisation/organisation_test.go
- return specific reason as to why there was a failure when creating an organisation
> chore: refactor organisation to return specific error codes

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/healthcrm_mock.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/service_mock.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- this refactor includes the services offered in a facility when it is created
- Additionally, it also includes the facility's business hours at the time of creating that facility
> chore: create facility assorted chores

- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/enums/ocl_terminologies.go
- pkg/mycarehub/application/enums/ocl_terminologies_test.go
- pkg/mycarehub/application/enums/week_days.go
- pkg/mycarehub/application/enums/week_days_test.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/facility/facility.go
- add weekday enums to be used when creating a facility with business hours
- add `CIEL` terminology source to be associated with a facility wen creating one
> chore: add terminology and day of the week enums

- go.mod
- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
- this API is used to fetch facilities that are close to me with regard to the program that i have currently selected
> feat: get nearby facilities

- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/input_test.go
- pkg/mycarehub/application/enums/country.go
- pkg/mycarehub/application/enums/country_test.go
- pkg/mycarehub/application/utils/csv.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- ensure that the services and business hours are returned when listing facilitiies
> fix: list facilities

- go.mod
- go.sum
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/healthcrm_mock.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/service_mock.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
- the API retrives all the services available in health crm
> feat: get all services

- .github/workflows/ci.yml
- .golangci.yaml
- .pre-commit-config.yaml
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/dto/output_test.go
- pkg/mycarehub/application/enums/client_type_test.go
- pkg/mycarehub/application/utils/helpers.go
- pkg/mycarehub/application/utils/helpers_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/presentation/cmd/service/mycarehubcmd.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/config_test.go
- pkg/mycarehub/usecases/communities/communities_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- pkg/mycarehub/usecases/securityquestions/security_question_unit_test.go
- pkg/mycarehub/usecases/securityquestions/security_questions.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/facility_acceptance_test.go
- fix rand package deprecation issue
> chore: add pre-commit hooks

- pkg/mycarehub/infrastructure/database/postgres/mappers.go
> chore: add county and address to facility response object

- go.mod
- go.sum
- pkg/mycarehub/application/enums/facility_identifier_type.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/healthcrm_mock.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/service_mock.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> feat: add nearby facilities retrieval feature

- go.mod
- go.sum
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/healthcrm_mock.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/service_mock.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
> chore: list provided healthcare services

- go.mod
- go.sum
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/healthcrm_mock.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/service_mock.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
Scenario: Given a healthcare service e.g Prep, return all facilities that offer Prep as a service
> feat: search facilities using a service name

- go.mod
- go.sum
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/input.graphql
- pkg/mycarehub/usecases/facility/facility_unit_test.go
This will help order the facilities response based on the facility proximity to the user
> chore: account for radius when fetching facilities

- db/migrations/000021_create_service_booking.down.sql
- db/migrations/000021_create_service_booking.up.sql
- fixtures/service_booking.yml
- go.mod
- go.sum
- pkg/mycarehub/domain/booking.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/config_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm_test.go
- pkg/mycarehub/infrastructure/services/healthcrm/mock/service_mock.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/config_fixtures.go
- tests/facility_acceptance_test.go
- API allows a user to do a booking of a particular service in a specified facility
> feat: book a service

- pkg/mycarehub/domain/facility.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
This allows a user to pass multiple service IDs then the response will be a list of facilities that offer those services
> chore: return facilities that offer a certain service

- go.mod
- go.sum
- pkg/mycarehub/domain/facility.go
- pkg/mycarehub/infrastructure/services/healthcrm/healthcrm.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
When coordinates are passed in the input, the response returns the distance to the facility from the user's location. If coordinates are missing, it defaults to 0.
> chore: return distance to facility

- pkg/mycarehub/application/enums/servicerequest_types.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/notification/messages.go
- fetches the count of bookings that are there when fetching service requests
> refactor: list booking(s) and booking(s) count

- pkg/mycarehub/application/enums/notification_types.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/notification/messages.go
- pkg/mycarehub/usecases/notification/messages_test.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- wire/provider.go
- creates a booking service request after client makes a booking
> refactor: create booking service request

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- tests/service_requests_acceptance_test.go
- wire/provider.go
- enables listing of booked services as part of service requests with the required customizations
Extras:
- add pagination to `getServiceRequests` API
> refactor: list booked services

- db/migrations/000023_add_booking_status.down.sql
- db/migrations/000023_add_booking_status.up.sql
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/application/enums/booking_code_status.go
- pkg/mycarehub/application/enums/booking_code_status_test.go
- pkg/mycarehub/domain/booking.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/tables.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
- pkg/mycarehub/usecases/facility/facility.go
Extra:
- add booking status enums
> refactor: add booking status column

- fixtures/clients_servicerequest.yml
- fixtures/service_booking.yml
- pkg/mycarehub/application/enums/booking_code_status.go
- pkg/mycarehub/infrastructure/database/postgres/pg_create.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/servicerequest.graphql
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- tests/service_requests_acceptance_test.go
- API is used to fulfil service booking. It marks the booking as fulfilled in the database
- Additionally, resolves the associated service request
> feat: complete visit

- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> fix: return service booking date

- fixtures/service_booking.yml
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
> refactor: list client bookings

- pkg/mycarehub/domain/servicerequest.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/presentation/graph/types.graphql
> chore: return username when fetching service requests

- deploy/charts/mycarehub-multitenant/templates/hpa.yaml
- deploy/charts/mycarehub-multitenant/values.yaml
> feat: add hpa resource for workloads scaling

- deploy/charts/mycarehub-multitenant/templates/deployment.yaml
- deploy/charts/mycarehub-multitenant/values.yaml
> chore: Adjust CPU and Memory Settings in Deployment

- deploy/charts/mycarehub-multitenant/templates/deployment.yaml
> chore: Update Container Resource Specifications

- deploy/charts/mycarehub-multitenant/templates/deployment.yaml
- deploy/charts/mycarehub-multitenant/templates/hpa.yaml
- deploy/charts/mycarehub-multitenant/values.yaml
> chore: update resource values

- pkg/mycarehub/usecases/facility/facility.go
> chore: append `booking id` when creating a booking service request

- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/presentation/graph/servicerequest.resolvers.go
- pkg/mycarehub/usecases/servicerequest/mock/mock.go
- pkg/mycarehub/usecases/servicerequest/servicerequest.go
- pkg/mycarehub/usecases/servicerequest/servicerequest_test.go
- tests/service_requests_acceptance_test.go
- concurrently fetches services from health crm by spawning workers that run concurrently and fetch services
> chore: fetch booking services

- deploy/charts/mycarehub-multitenant/templates/mycarehub_app.yaml
> chore: remove is_local_db variable from deployment

- pkg/mycarehub/application/enums/booking_code_status.go
- pkg/mycarehub/application/enums/booking_code_status_test.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/graph/enums.graphql
- pkg/mycarehub/presentation/graph/facility.graphql
- pkg/mycarehub/presentation/graph/facility.resolvers.go
- pkg/mycarehub/presentation/graph/generated/generated.go
- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- pkg/mycarehub/usecases/facility/mock/facility_mock.go
- tests/facility_acceptance_test.go
- fetch upcoming and past bookings based on time. For a booking to be considered missed, the client ought to be late by more that 8 hours. Fetches all the bookings irregardles of its status, i.e whether `PENDING` OR `FULFILLED`.
- upcoming bookings are the deemed to be as from -8 hours from current time. The booking also has to be `PENDING`
- Indicate any breakages caused in the UI …
> refactor: list client booking

- .github/workflows/multitenant-deploy.yaml
> chore: update gke github action

- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query_unit_test.go
> chore: remove unnecessary fetching of user profile

- deploy/charts/mycarehub-multitenant/templates/mycarehub_database.yaml
- pkg/mycarehub/infrastructure/database/postgres/gorm/db_connection.go
> chore: add pgbouncer environment variables

- go.mod
- go.sum
> chore: update healthcrm version

- pkg/mycarehub/usecases/facility/facility.go
- pkg/mycarehub/usecases/facility/facility_unit_test.go
- remove the action of checking if the facility existed in MCH
> fix: fetch facility by ID from health CRM.

- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/content/content.go
- pkg/mycarehub/usecases/content/content_unit_test.go
- pkg/mycarehub/usecases/content/mock/content_mock.go
- tests/content_acceptance_test.go
- used to retrieve content for unauthenticated users so that they are able to view educative content
> feat: fetch content

- .github/workflows/ci.yml
- .github/workflows/multitenant-deploy.yaml
- db/migrations/000024_alter_clients_client.down.sql
- db/migrations/000024_alter_clients_client.up.sql
- deploy/charts/mycarehub-multitenant/templates/mycarehub_app.yaml
- deploy/deploy.sh
- pkg/mycarehub/application/dto/input.go
- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/create.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/usecases/user/mock/user_mock.go
- pkg/mycarehub/usecases/user/user.go
- pkg/mycarehub/usecases/user/user_unit_test.go
- tests/user_acceptance_test.go
- refactor the API to support client self-onboarding
> refactor: client registration

- data/facilities.csv
- pkg/mycarehub/application/utils/csv.go
> fix: fix load facilities from file

- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
> feat: add get services rest endpoint

- pkg/mycarehub/application/dto/output.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/mock/gorm_mock.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query.go
- pkg/mycarehub/infrastructure/database/postgres/gorm/query_test.go
- pkg/mycarehub/infrastructure/database/postgres/mock/pg_mock.go
- pkg/mycarehub/infrastructure/database/postgres/pg_query.go
- pkg/mycarehub/infrastructure/repository.go
- pkg/mycarehub/presentation/config.go
- pkg/mycarehub/presentation/rest/handlers.go
- pkg/mycarehub/presentation/rest/handlers_test.go
- pkg/mycarehub/usecases/questionnaires/mock/questionnaires_mock.go
- pkg/mycarehub/usecases/questionnaires/questionnaires.go
- pkg/mycarehub/usecases/questionnaires/questionnaires_test.go
> feat: add get all screening tools
